### ISSUE TITLE
Feature request: don't base-url local references

### ISSUE THREAD

**Issue by jceb** [markedjs/marked-base-url#112]
I recently ran into a issue with a reference to an anchor tag in the local document that was also put on the base url. Since the tag is local, i.e. `.href.startsWith('#')`, to the currently viewed document, could marked-base-url be changed to not put the base url in front?

Current behavior:

```javascript
marked.parse("[local link](#anchor)");
'<p><a href="https://example.com/folder/#anchor">local link</a></p>\n'
```

Desired new behavior:

```javascript
marked.parse("[local link](#anchor)");
'<p><a href="#anchor">local link</a></p>\n'
```

**Comment by UziTech** [comment]
That seems reasonable. If you want to create a PR I would approve it.
