### ISSUE TITLE
Dealing with changing `baseUrl`s

### ISSUE THREAD

**Issue by georggrab** [markedjs/marked-base-url#129]
Hi guys,

first of all, thanks for `marked`, it's awesome.
I'm in the process of upgrading a personal app from `"marked": "^1.2.8",`, and it's easy sailing, except for the thing where the `baseUrl` option was removed from the main parsing function (https://github.com/markedjs/marked/pull/2936).

My app has changing baseUrls depending on the document I'm trying to parse. With the previous atomic formulation `marked(doc, {baseUrl: theBaseUrlOfDoc})`, this was no problem, but I have some issues incorporating the new way of doing things, which I guess amounts to `marked.use(baseUrl(theBaseUrlOfDoc))` followed by `marked.parse(doc)`. It's like the new baseUrl is not applied properly and multiple (updating) calls marked.use are not supported.

Can you point me in the right direction with regards to upgrading this usecase to your changed plugin-based API? Any hints greatly appreciated. For now, I'm stuck upgrading to `^7` which doesn't have this breaking change.

Cheers, Georg

**Comment by UziTech** [comment]
You can create a [Marked instance](https://marked.js.org/using_advanced#instance) when you create a new baseUrl

```js
import { Marked } from 'marked';
import {baseUrl} from "marked-base-url";

for (const doc of docs) {
  const marked = new Marked(baseUrl(doc.baseUrl));
  const html = marked.parse(doc.markdown);
}
```

**Comment by georggrab** [comment]
Welp, that solves it of course! I was ignorant of the fact that Marked instances were a thing.
Thanks a lot, @UziTech !
