### ISSUE TITLE
maybe we need a index.d.ts

### ISSUE THREAD

**Issue by sinotaotao** [markedjs/marked-base-url#76]
there is a node_modules\marked-highlight\src\index.d.ts file in marked-highlight npm package. but this project has no this d.ts file. Please add it for TypeScript

**Comment by UziTech** [comment]
PRs are welcome 😁👍

#67 was started but never finished. If someone wants to continue that work we can merge it.

**Comment by sinotaotao** [comment]
#77 #67 will fix this issue
